dataset: medium-replay
device: cuda
env: metaworld_button-press-topdown-v2
feedback_num: 1000
data_quality: 1.0
segment_size: 25
normalize: true
threshold: 0.5
data_aug: none
q_budget: 1
feedback_type: RLT
model_type: BT
noise: 0.0
human: false
epochs: 1000
batch_size: 256
activation: tanh
lr: 1e-3
hidden_sizes: 200
ensemble_num: 7
ensemble_method: mean